require 'slack-ruby-bot-server'
require 'mailchimp_api_v3'
require 'slack-ruby-bot-server/mailchimp/version'
require 'slack-ruby-bot-server/mailchimp/config'
require 'slack-ruby-bot-server/mailchimp/lifecycle'
